---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sshd-jumpserver
spec:
  replicas: 1
  template:
    metadata:
      name: sshd-jumpserver
      labels:
        app: sshd-jumpserver
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: sshd-jumpserver
          image: portertech/sshd-jumpserver:1.0.0
          ports:
            - containerPort: 2222
              protocol: TCP
          env:
            - name: SSHD_PORT
              value: "2222"
            - name: PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: sshkey
                  key: authorizedkeys
