---
apiVersion: v1
kind: Service
metadata:
  name: sshd-jumpserver
  labels:
    name: sshd-jumpserver
spec:
  type: "LoadBalancer"
  selector:
    app: sshd-jumpserver
  ports:
    - name: ssh
      port: 22
      targetPort: 2222
